### ISSUE TITLE
Requirements.txt file has local files 

### ISSUE THREAD

**Issue by evangorstein** [naity/protein-transformer#1]
It looks like your `requirements.txt` file has a bunch of local file-paths. So for example, when I try to download the requirements with `pip install -r requirements.txt`, I get the error message:

```
Processing /home/conda/feedstock_root/build_artifacts/asttokens_1698341106958/work (from -r requirements.txt (line 9))
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/System/Volumes/Data/home/conda/feedstock_root/build_artifacts/asttokens_1698341106958/work'
```

**Comment by naity** [comment]
> It looks like your `requirements.txt` file has a bunch of local file-paths. So for example, when I try to download the requirements with `pip install -r requirements.txt`, I get the error message:
> 
> ```
> Processing /home/conda/feedstock_root/build_artifacts/asttokens_1698341106958/work (from -r requirements.txt (line 9))
> ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/System/Volumes/Data/home/conda/feedstock_root/build_artifacts/asttokens_1698341106958/work'
> ```

Fixed. Thank you!
